"""Populate the quotes collection with a curated set of real, attributed quotes.

Usage (from backend/, with the virtual environment active):
    python scripts/seed_quotes.py
"""
from __future__ import annotations

import os

from dotenv import find_dotenv, load_dotenv
from pymongo import MongoClient

load_dotenv(find_dotenv(usecwd=True))

MONGO_URI = os.environ.get("MONGO_URI", "mongodb://localhost:27017/taskly")

QUOTES = [
    {"text": "You may encounter many defeats, but you must not be defeated.", "author": "Maya Angelou"},
    {"text": "Nothing will work unless you do.", "author": "Maya Angelou"},
    {"text": "Do the best you can until you know better. Then when you know better, do better.", "author": "Maya Angelou"},
    {"text": "You must do the thing you think you cannot do.", "author": "Eleanor Roosevelt"},
    {"text": "It takes as much energy to wish as it does to plan.", "author": "Eleanor Roosevelt"},
    {"text": "Nothing in life is to be feared, it is only to be understood.", "author": "Marie Curie"},
    {"text": "I was taught that the way of progress was neither swift nor easy.", "author": "Marie Curie"},
    {"text": "One never notices what has been done; one can only see what remains to be done.", "author": "Marie Curie"},
    {"text": "Life is not easy for any of us. But what of that? We must have perseverance and above all confidence in ourselves.", "author": "Marie Curie"},
    {"text": "Alone we can do so little; together we can do so much.", "author": "Helen Keller"},
    {"text": "Optimism is the faith that leads to achievement.", "author": "Helen Keller"},
    {"text": "The most difficult thing is the decision to act, the rest is merely tenacity.", "author": "Amelia Earhart"},
    {"text": "Preparation, I have often said, is rightly two-thirds of any venture.", "author": "Amelia Earhart"},
    {"text": "The most effective way to do it, is to do it.", "author": "Amelia Earhart"},
    {"text": "You must never be fearful about what you are doing when it is right.", "author": "Rosa Parks"},
    {"text": "Turn your wounds into wisdom.", "author": "Oprah Winfrey"},
    {"text": "The biggest adventure you can take is to live the life of your dreams.", "author": "Oprah Winfrey"},
    {"text": "You get in life what you have the courage to ask for.", "author": "Oprah Winfrey"},
    {"text": "Real change, enduring change, happens one step at a time.", "author": "Ruth Bader Ginsburg"},
    {"text": "Am I good enough? Yes, I am.", "author": "Michelle Obama"},
    {"text": "There is no limit to what we, as women, can accomplish.", "author": "Michelle Obama"},
    {"text": "Success isn't about how much money you make; it's about the difference you make in people's lives.", "author": "Michelle Obama"},
    {"text": "In order to be irreplaceable, one must always be different.", "author": "Coco Chanel"},
    {"text": "Success is often achieved by those who don't know that failure is inevitable.", "author": "Coco Chanel"},
    {"text": "Nothing is impossible, the word itself says 'I'm possible'!", "author": "Audrey Hepburn"},
    {"text": "I believe in being strong when everything seems to be going wrong.", "author": "Audrey Hepburn"},
    {"text": "I alone cannot change the world, but I can cast a stone across the water to create many ripples.", "author": "Mother Teresa"},
    {"text": "Do not wait for leaders; do it alone, person to person.", "author": "Mother Teresa"},
    {"text": "I attribute my success to this: I never gave or took any excuse.", "author": "Florence Nightingale"},
    {"text": "There are two kinds of people: those who do the work and those who take the credit.", "author": "Indira Gandhi"},
    {"text": "Change your life today. Don't gamble on the future, act now, without delay.", "author": "Simone de Beauvoir"},
    {"text": "Failure is impossible.", "author": "Susan B. Anthony"},
    {"text": "I've been absolutely terrified every moment of my life, and I've never let it keep me from doing a single thing I wanted to do.", "author": "Georgia O'Keeffe"},
    {"text": "Making your unknown known is the important thing.", "author": "Georgia O'Keeffe"},
    {"text": "A ship in port is safe, but that is not what ships are built for.", "author": "Grace Hopper"},
    {"text": "The most dangerous phrase in the language is, 'We've always done it this way.'", "author": "Grace Hopper"},
    {"text": "One accurate measurement is worth a thousand expert opinions.", "author": "Grace Hopper"},
    {"text": "Done is better than perfect.", "author": "Sheryl Sandberg"},
    {"text": "What would you do if you weren't afraid?", "author": "Sheryl Sandberg"},
    {"text": "We need to accept that failure is not the opposite of success, it's part of success.", "author": "Arianna Huffington"},
    {"text": "Vulnerability is the birthplace of innovation, creativity and change.", "author": "Brené Brown"},
    {"text": "Courage starts with showing up and letting ourselves be seen.", "author": "Brené Brown"},
    {"text": "Never underestimate the power of dreams and the influence of the human spirit.", "author": "Wilma Rudolph"},
    {"text": "I really think a champion is defined not by their wins but by how they can recover when they fall.", "author": "Serena Williams"},
    {"text": "I've grown most not from victories, but from setbacks.", "author": "Serena Williams"},
    {"text": "What you do makes a difference, and you have to decide what kind of difference you want to make.", "author": "Jane Goodall"},
    {"text": "Every individual matters. Every individual has a role to play. Every individual makes a difference.", "author": "Jane Goodall"},
    {"text": "I didn't know exactly what I wanted to do, but I knew the kind of woman I wanted to be.", "author": "Diane von Furstenberg"},
    {"text": "I am not afraid of storms, for I am learning how to sail my ship.", "author": "Louisa May Alcott"},
    {"text": "You need to trust yourself, especially in a world that is constantly trying to get you to be somebody else.", "author": "Elizabeth Gilbert"},
    {"text": "Life shrinks or expands in proportion to one's courage.", "author": "Anaïs Nin"},
    {"text": "Our deepest fear is not that we are inadequate. Our deepest fear is that we are powerful beyond measure.", "author": "Marianne Williamson"},
    {"text": "To love what you do and feel that it matters — how could anything be more fun?", "author": "Katharine Graham"},
    {"text": "I don't know the secret to success, but the key to failure is trying to please everyone.", "author": "Estée Lauder"},
    {"text": "Above all, be the heroine of your life, not the victim.", "author": "Nora Ephron"},
    {"text": "I don't think about my legacy. I'm too busy working.", "author": "Anna Wintour"},
    {"text": "Just because you are CEO, don't think you have landed. You must continually increase your learning.", "author": "Indra Nooyi"},
    {"text": "I always did something I was a little not ready to do. I think that's how you grow.", "author": "Marissa Mayer"},
    {"text": "It's okay to fail. If you're not failing, you're not growing.", "author": "Marissa Mayer"},
    {"text": "You can have it all, just not all at once.", "author": "Melinda Gates"},
    {"text": "Great people do things before they're ready.", "author": "Amy Poehler"},
    {"text": "Enthusiasm is common. Endurance is rare.", "author": "Angela Duckworth"},
    {"text": "Like what you do, and then you will do your best.", "author": "Katherine Johnson"},
    {"text": "Giving up on being perfect and beginning the work of becoming yourself is really hard and really amazing.", "author": "Anna Quindlen"},
    {"text": "Find something you're passionate about and keep tremendously interested in it.", "author": "Julia Child"},
    {"text": "The way I see it, if you want the rainbow, you gotta put up with the rain.", "author": "Dolly Parton"},
    {"text": "I'd rather regret the risks that didn't work out than the chances I didn't take at all.", "author": "Simone Biles"},
    {"text": "Champions keep playing until they get it right.", "author": "Billie Jean King"},
    {"text": "Don't be intimidated by what you don't know. That can be your greatest strength.", "author": "Sara Blakely"},
    {"text": "What you got to have is faith and discipline when you're not yet a winner.", "author": "Debbi Fields"},
    {"text": "Risk! Risk anything! Do the hardest thing on earth for you. Act for yourself.", "author": "Katherine Mansfield"},
    {"text": "It is not easy to be a pioneer — but oh, it is fascinating!", "author": "Elizabeth Blackwell"},
    {"text": "You want to fly, you have to give up the things that weigh you down.", "author": "Toni Morrison"},
    {"text": "Energy rightly applied and directed will accomplish anything.", "author": "Nellie Bly"},
    {"text": "Growth and comfort do not coexist.", "author": "Ginni Rometty"},
    {"text": "Life is like riding a bicycle. To keep your balance, you must keep moving.", "author": "Albert Einstein"},
    {"text": "In the middle of difficulty lies opportunity.", "author": "Albert Einstein"},
    {"text": "A person who never made a mistake never tried anything new.", "author": "Albert Einstein"},
    {"text": "It always seems impossible until it's done.", "author": "Nelson Mandela"},
    {"text": "I never lose. I either win or learn.", "author": "Nelson Mandela"},
    {"text": "The future depends on what you do today.", "author": "Mahatma Gandhi"},
    {"text": "You must be the change you wish to see in the world.", "author": "Mahatma Gandhi"},
    {"text": "Faith is taking the first step even when you don't see the whole staircase.", "author": "Martin Luther King Jr."},
    {"text": "Genius is one percent inspiration and ninety-nine percent perspiration.", "author": "Thomas Edison"},
    {"text": "I have not failed. I've just found 10,000 ways that won't work.", "author": "Thomas Edison"},
    {"text": "Opportunity is missed by most people because it is dressed in overalls and looks like work.", "author": "Thomas Edison"},
    {"text": "There is no substitute for hard work.", "author": "Thomas Edison"},
    {"text": "Your work is going to fill a large part of your life, and the only way to be truly satisfied is to do what you believe is great work.", "author": "Steve Jobs"},
    {"text": "Stay hungry, stay foolish.", "author": "Steve Jobs"},
    {"text": "The only way to do great work is to love what you do.", "author": "Steve Jobs"},
    {"text": "By failing to prepare, you are preparing to fail.", "author": "Benjamin Franklin"},
    {"text": "An investment in knowledge pays the best interest.", "author": "Benjamin Franklin"},
    {"text": "Well done is better than well said.", "author": "Benjamin Franklin"},
    {"text": "We are what we repeatedly do. Excellence, then, is not an act, but a habit.", "author": "Aristotle"},
    {"text": "It does not matter how slowly you go as long as you do not stop.", "author": "Confucius"},
    {"text": "Our greatest glory is not in never falling, but in rising every time we fall.", "author": "Confucius"},
    {"text": "Learning never exhausts the mind.", "author": "Leonardo da Vinci"},
    {"text": "Never mistake motion for action.", "author": "Ernest Hemingway"},
    {"text": "Whether you think you can, or you think you can't – you're right.", "author": "Henry Ford"},
    {"text": "Coming together is a beginning; keeping together is progress; working together is success.", "author": "Henry Ford"},
    {"text": "The way to get started is to quit talking and begin doing.", "author": "Walt Disney"},
    {"text": "All our dreams can come true, if we have the courage to pursue them.", "author": "Walt Disney"},
    {"text": "Do what you can, with what you have, where you are.", "author": "Theodore Roosevelt"},
    {"text": "Nothing worth having comes easy.", "author": "Theodore Roosevelt"},
    {"text": "Perfect is the enemy of good.", "author": "Voltaire"},
    {"text": "Do not go where the path may lead, go instead where there is no path and leave a trail.", "author": "Ralph Waldo Emerson"},
    {"text": "The only person you are destined to become is the person you decide to be.", "author": "Ralph Waldo Emerson"},
    {"text": "Go confidently in the direction of your dreams. Live the life you have imagined.", "author": "Henry David Thoreau"},
    {"text": "Great things are done by a series of small things brought together.", "author": "Vincent van Gogh"},
    {"text": "I am seeking, I am striving, I am in it with all my heart.", "author": "Vincent van Gogh"},
    {"text": "Action is the foundational key to all success.", "author": "Pablo Picasso"},
    {"text": "Only put off until tomorrow what you are willing to die having left undone.", "author": "Pablo Picasso"},
    {"text": "I fear not the man who has practiced 10,000 kicks once, but I fear the man who has practiced one kick 10,000 times.", "author": "Bruce Lee"},
    {"text": "Do not pray for an easy life, pray for the strength to endure a difficult one.", "author": "Bruce Lee"},
    {"text": "A goal is not always meant to be reached, it often serves simply as something to aim at.", "author": "Bruce Lee"},
    {"text": "A journey of a thousand miles begins with a single step.", "author": "Lao Tzu"},
    {"text": "Luck is what happens when preparation meets opportunity.", "author": "Seneca"},
    {"text": "It is not that we have a short time to live, but that we waste a lot of it.", "author": "Seneca"},
    {"text": "The impediment to action advances action. What stands in the way becomes the way.", "author": "Marcus Aurelius"},
    {"text": "Efforts and courage are not enough without purpose and direction.", "author": "John F. Kennedy"},
    {"text": "The best way to predict the future is to create it.", "author": "Peter Drucker"},
    {"text": "Efficiency is doing things right; effectiveness is doing the right things.", "author": "Peter Drucker"},
    {"text": "What gets measured gets managed.", "author": "Peter Drucker"},
    {"text": "The key is not to prioritize what's on your schedule, but to schedule your priorities.", "author": "Stephen Covey"},
    {"text": "You don't have to be great to start, but you have to start to be great.", "author": "Zig Ziglar"},
    {"text": "It's not what happens to you, but how you handle it that counts.", "author": "Zig Ziglar"},
    {"text": "The present is theirs; the future, for which I really worked, is mine.", "author": "Nikola Tesla"},
    {"text": "Don't count the days, make the days count.", "author": "Muhammad Ali"},
    {"text": "I hated every minute of training, but I said, 'Don't quit. Suffer now and live the rest of your life as a champion.'", "author": "Muhammad Ali"},
    {"text": "Champions aren't made in gyms. Champions are made from something they have deep inside them.", "author": "Muhammad Ali"},
    {"text": "Discipline is the bridge between goals and accomplishment.", "author": "Jim Rohn"},
    {"text": "Either you run the day, or the day runs you.", "author": "Jim Rohn"},
    {"text": "Someone is sitting in the shade today because someone planted a tree a long time ago.", "author": "Warren Buffett"},
    {"text": "If I have seen further, it is by standing on the shoulders of giants.", "author": "Isaac Newton"},
    {"text": "Success is to be measured not so much by the position that one has reached in life as by the obstacles which he has overcome.", "author": "Booker T. Washington"},
    {"text": "If there is no struggle, there is no progress.", "author": "Frederick Douglass"},
    {"text": "The best way to not feel hopeless is to get up and do something.", "author": "Barack Obama"},
    {"text": "Do not be embarrassed by your failures, learn from them and start again.", "author": "Richard Branson"},
    {"text": "It's fine to celebrate success, but it is more important to heed the lessons of failure.", "author": "Bill Gates"},
    {"text": "A dream doesn't become reality through magic; it takes sweat, determination and hard work.", "author": "Colin Powell"},
    {"text": "There are no secrets to success. It is the result of preparation, hard work and learning from failure.", "author": "Colin Powell"},
    {"text": "If you don't understand the details of your business, you are going to fail.", "author": "Jeff Bezos"},
    {"text": "The path to success is to take massive, determined action.", "author": "Tony Robbins"},
    {"text": "Whatever the mind can conceive and believe, it can achieve.", "author": "Napoleon Hill"},
    {"text": "Amateurs sit and wait for inspiration, the rest of us just get up and go to work.", "author": "Stephen King"},
    {"text": "The dictionary is the only place that success comes before work.", "author": "Vince Lombardi"},
    {"text": "I've missed more than 9,000 shots in my career. I've failed over and over again, and that is why I succeed.", "author": "Michael Jordan"},
    {"text": "Ninety-nine percent of the failures come from people who have the habit of making excuses.", "author": "George Washington Carver"},
    {"text": "Most of the important things in the world have been accomplished by people who kept on trying when there seemed to be no hope at all.", "author": "Dale Carnegie"},
    {"text": "Do not let what you cannot do interfere with what you can do.", "author": "John Wooden"},
    {"text": "In any given moment we have two options: to step forward into growth or to step back into safety.", "author": "Abraham Maslow"},
    {"text": "The battles that count aren't the ones for gold medals — the struggles within yourself are where it's at.", "author": "Jesse Owens"},
    {"text": "The most important thing is to try and inspire people so that they can be great in whatever they want to do.", "author": "Kobe Bryant"},
    {"text": "Start where you are. Use what you have. Do what you can.", "author": "Arthur Ashe"},
    {"text": "Before anything else, preparation is the key to success.", "author": "Alexander Graham Bell"},
    {"text": "Never give up. Today is hard, tomorrow will be worse, but the day after tomorrow will be sunshine.", "author": "Jack Ma"},
    {"text": "I find that the harder I work, the more luck I seem to have.", "author": "Thomas Jefferson"},
    {"text": "The best and most beautiful things in the world cannot be seen or even touched — they must be felt with the heart.", "author": "Helen Keller"},
    {"text": "Keep your face to the sunshine and you cannot see the shadow.", "author": "Helen Keller"},
    {"text": "Dwell in possibility.", "author": "Emily Dickinson"},
    {"text": "Not knowing when the dawn will come, I open every door.", "author": "Emily Dickinson"},
    {"text": "Forever is composed of nows.", "author": "Emily Dickinson"},
    {"text": "Where there's hope, there's life.", "author": "Anne Frank"},
    {"text": "Feet, what do I need you for when I have wings to fly?", "author": "Frida Kahlo"},
    {"text": "At the end of the day, we can endure much more than we think we can.", "author": "Frida Kahlo"},
    {"text": "I've learned that people will forget what you said, people will forget what you did, but people will never forget how you made them feel.", "author": "Maya Angelou"},
    {"text": "You cannot find peace by avoiding life.", "author": "Virginia Woolf"},
    {"text": "The most important relationship you have in life is the relationship you have with yourself.", "author": "Diane von Furstenberg"},
    {"text": "Almost everything will work again if you unplug it for a few minutes, including you.", "author": "Anne Lamott"},
    {"text": "We are living in a work culture that treats burnout as the price we must pay for success.", "author": "Arianna Huffington"},
    {"text": "The most important thing is to enjoy your life — to be happy — it's all that matters.", "author": "Audrey Hepburn"},
    {"text": "Happiness is not a goal, it is a by-product.", "author": "Eleanor Roosevelt"},
    {"text": "Nothing ever goes away until it has taught us what we need to know.", "author": "Pema Chödrön"},
    {"text": "You are the sky. Everything else is just the weather.", "author": "Pema Chödrön"},
    {"text": "Life is really simple, but we insist on making it complicated.", "author": "Louise Hay"},
    {"text": "And the day came when the risk to remain tight in a bud was more painful than the risk it took to blossom.", "author": "Anaïs Nin"},
    {"text": "Breathe. Let go. And remind yourself that this very moment is the only one you know you have for sure.", "author": "Oprah Winfrey"},
    {"text": "Peace begins with a smile.", "author": "Mother Teresa"},
    {"text": "The really happy person is the one who can enjoy the scenery on a detour.", "author": "Doris Day"},
    {"text": "Laugh, and the world laughs with you; weep, and you weep alone.", "author": "Ella Wheeler Wilcox"},
    {"text": "Carry out a random act of kindness, with no expectation of reward.", "author": "Diana, Princess of Wales"},
    {"text": "Hate is too great a burden to bear.", "author": "Coretta Scott King"},
    {"text": "It's not what you look at that matters, it's what you see.", "author": "Henry David Thoreau"},
    {"text": "You have power over your mind — not outside events. Realize this, and you will find strength.", "author": "Marcus Aurelius"},
    {"text": "It's not what happens to you, but how you react to it that matters.", "author": "Epictetus"},
    {"text": "Who looks outside, dreams; who looks inside, awakes.", "author": "Carl Jung"},
    {"text": "Everything that irritates us about others can lead us to an understanding of ourselves.", "author": "Carl Jung"},
    {"text": "The only true wisdom is in knowing you know nothing.", "author": "Socrates"},
    {"text": "Knowing yourself is the beginning of all wisdom.", "author": "Aristotle"},
    {"text": "What lies behind us and what lies before us are tiny matters compared to what lies within us.", "author": "Ralph Waldo Emerson"},
    {"text": "Every new beginning comes from some other beginning's end.", "author": "Seneca"},
    {"text": "Nature does not hurry, yet everything is accomplished.", "author": "Lao Tzu"},
    {"text": "Simplicity is the ultimate sophistication.", "author": "Leonardo da Vinci"},
    {"text": "Hold fast to dreams, for if dreams die, life is a broken-winged bird that cannot fly.", "author": "Langston Hughes"},
    {"text": "Time and health are two precious assets that we don't recognize and appreciate until they have been depleted.", "author": "Denis Waitley"},
    {"text": "Sometimes your joy is the source of your smile, but sometimes your smile can be the source of your joy.", "author": "Thich Nhat Hanh"},
    {"text": "Happiness is not something ready-made. It comes from your own actions.", "author": "Dalai Lama"},
    {"text": "The quieter you become, the more you can hear.", "author": "Rumi"},
    {"text": "There are three ways to ultimate success: The first way is to be kind. The second way is to be kind. The third way is to be kind.", "author": "Fred Rogers"},
    {"text": "You can't stop the waves, but you can learn to surf.", "author": "Jon Kabat-Zinn"},
]


def seed() -> None:
    db = MongoClient(MONGO_URI).get_default_database()
    db.quotes.delete_many({})
    db.quotes.insert_many(QUOTES)
    print(f"Seeded {len(QUOTES)} quotes into '{db.name}.quotes'.")


if __name__ == "__main__":
    seed()
